name: demo_execute_001
on: workflow_dispatch

jobs:
  first-job: # custom name - anything you want
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello World"
      - name: how_are_you
        run: echo "How are you?"
